### ISSUE TITLE
Duplicate comment when converting back from document

### ISSUE THREAD

**Issue by zoroaster00** [mohsen1/yawn-yaml#25]
The yaml will contain duplicate comment when converting the parsed document by "toString"
Example:
```
test1:
  foo: #123
    bar: 1
```
After converting to document and toString
```
test1:
  foo: #123
    #123
    bar: 1
```
